Import('*')

SimObject('CustomObj.py', sim_objects=['CustomObj'])
SimObject('CustomCounter.py', sim_objects=['CustomCounter'])


Source('custom_obj.cc')
Source('custom_counter.cc')

DebugFlag('CustomObj', "Custom Inst")

